// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD9ihyHLXyXaxPJiryuOeePQ5IcNNo-gNw',
    appId: '1:877334850068:web:9a10b00a7bd231dd4a9501',
    messagingSenderId: '877334850068',
    projectId: 'sunote-40266',
    authDomain: 'sunote-40266.firebaseapp.com',
    storageBucket: 'sunote-40266.firebasestorage.app',
    measurementId: 'G-51BVP9B851',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0bMQp0_Jsix8cGV2j1D6UuEZePNgY9Wg',
    appId: '1:877334850068:android:4fc14865ed0522a54a9501',
    messagingSenderId: '877334850068',
    projectId: 'sunote-40266',
    storageBucket: 'sunote-40266.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBCs5DXqLK-pMwzNtIrL75wXNllNQcIfQI',
    appId: '1:877334850068:ios:eddd83a546eb25ad4a9501',
    messagingSenderId: '877334850068',
    projectId: 'sunote-40266',
    storageBucket: 'sunote-40266.firebasestorage.app',
    iosBundleId: 'com.example.cs310sunote',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBCs5DXqLK-pMwzNtIrL75wXNllNQcIfQI',
    appId: '1:877334850068:ios:eddd83a546eb25ad4a9501',
    messagingSenderId: '877334850068',
    projectId: 'sunote-40266',
    storageBucket: 'sunote-40266.firebasestorage.app',
    iosBundleId: 'com.example.cs310sunote',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyD9ihyHLXyXaxPJiryuOeePQ5IcNNo-gNw',
    appId: '1:877334850068:web:34ac99f64e59c0064a9501',
    messagingSenderId: '877334850068',
    projectId: 'sunote-40266',
    authDomain: 'sunote-40266.firebaseapp.com',
    storageBucket: 'sunote-40266.firebasestorage.app',
    measurementId: 'G-ZL3W03E1JV',
  );
}
